name: "segmentation_model_post_deeplabv3"
platform: "pytorch_libtorch"
max_batch_size: 8
input [
    {
        name: "input_image"
        data_type: TYPE_FP32
        dims: [ 3, 512, 512 ]
    }
]
output [
    {
        name: "logits"
        data_type: TYPE_FP32
        dims: [  7, 512, 512 ]
    }
]